#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=2

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"
chmod +x $install_dir/metabase.jar

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGNX web server..." --weight=3

# Create a dedicated NGINX config
ynh_add_nginx_config

ynh_add_systemd_config

# Use logrotate to manage application logfile(s)
ynh_use_logrotate

yunohost service add $app --description="Web database management tool" --log="/var/log/$app/$app.log"

#=================================================
# SETUP CONFIG
#=================================================
ynh_script_progression --message="Adding a configuration file..." --weight=1

touch /etc/default/$app
ynh_add_config --template="../conf/metabase" --destination="/etc/default/$app"

chmod 640 "/etc/default/$app"
chown $app "/etc/default/$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=2

# Start a systemd service
ynh_systemd_action --service_name=$app --action=start --log_path=systemd --line_match="Please use the following URL to setup your Metabase installation:"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
